server:
  port: 8091
  port-api-gateway: 8082

keycloak:
  realm_id: c605f551-0683-47d1-bf82-7306fc5e16ca

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
      generate-ddl: true
      show-sql: true # Uncomment to enable SQL logging
#      database: postgresql
#      open-in-view: false
#      properties:
#        hibernate:
#          default_schema: salon
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/salon"
          jwk-set-uri: "http://localhost:8180/realms/salon/protocol/openid-connect/certs"
  application:
    name: eureka-hairdresser

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka