server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  cloud:
    gateway:
      default-filters: TokenRelay=
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: profile-client
          uri: lb://eureka-client
          predicates:
            - Path=/client/**
        - id: profile-hairdresser
          uri: lb://eureka-hairdresser
          predicates:
            - Path=/hairdresser/**
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            client-id: "api-gateway"
            client-secret: "0FbfJDquyw2DlAQLPW41gxEjpUC23bBq"
            provider: "api-gateway"
            scope:
              - "openid"
              - "profile"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
        provider:
          api-gateway:
            issuer-uri: "http://localhost:8180/realms/salon"
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/salon"

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
