server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
#  config:
#    import: optional:configserver:http://localhost:8083
  cloud:
#    config:
#      uri: http://localhost:8083
    gateway:
      default-filters: TokenRelay=
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://eureka-client
          predicates:
            - Path=/test
            - Method=GET
        - id: driverr-test
          uri: lb://eureka-client
          predicates:
            - Path=/driver
            - Method=GET
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            client-id: "api-gateway"
            client-secret: "0FbfJDquyw2DlAQLPW41gxEjpUC23bBq"
            provider: "api-gateway"
            scope:
              - "openid"
              - "profile"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
        provider:
          api-gateway:
            issuer-uri: "http://localhost:8180/realms/salon"
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/salon"
