server:
  port: 8082

spring:
  config:
    import: optional:configserver:http://localhost:8083
  cloud:
    config:
      uri: http://localhost:8083
    gateway:
      default-filters: TokenRelay=
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            client-id: "api-gateway"
            client-secret: "0FbfJDquyw2DlAQLPW41gxEjpUC23bBq"
            provider: "api-gateway"
            scope:
              - "openid"
              - "profile"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
        provider:
          api-gateway:
            issuer-uri: "http://localhost:8180/realms/salon"
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/salon"
