server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/salon"
          jwk-set-uri: "http://localhost:8180/realms/salon/protocol/openid-connect/certs"
  config:
    import: optional:configserver:http://localhost:8083
  cloud:
    config:
      uri: http://localhost:8083
  application:
    name: eureka-client
